[model]
path = "/media/wlutz/TOSHIBA EXT/Electrical activity analysis/EV_GW/MODELS/DisabledFlow Harmonics filtered ctl t16 vs gw_noev t16.rfc"  # a trained model
train = ["DisabledFlow Ctl T=16" , "DisabledFlow GW_NoEV T=16", ]
test = ["DisabledFlow Ctl T=16" , "DisabledFlow GW_NoEV T=16", "DisabledFlow NoGW_EV T=16", "DisabledFlow GW_EV T=16", ]

[dataset]
path = "/media/wlutz/TOSHIBA EXT/Electrical activity analysis/EV_GW/DATASETS/Dataset_DisabledFlow_all_conditions_harmonics_filtered_merged_hours_Xy_test.csv"
target_column = "label"

[figure]
iterations = 3
mode = "percent"
show = true
dpi = 600
save = "" # empty to disable
export_data = "/media/wlutz/TOSHIBA EXT/Electrical activity analysis/EV_GW/RESULTS/confusion results.csv" # empty to disable. '.csv' extension required

width = 8
height = 8
font = "DejaVu Sans"
    [figure.title]
    label = "Effect of EVs on electrical activity"
    size = 16

    [figure.cbar] # color bar
    shrink =  0.5
    location = 'right'

    [figure.annot]  # scores and CUP
    size = 12

    [figure.axes]
    split_labels = " "
    xlabel = "The input is classified as"
    xsize = 12
    ylabel = "The input is"
    ysize = 12

    [figure.ticks]
    xrot = 0
    xsize = 12
    yrot = 0
    ysize = 12


