[model]
path = "/media/wlutz/TOSHIBA EXT/Electrical activity analysis/EV_GW/MODELS/DisabledFlow Harmonics filtered ctl t16 vs gw_noev t16.rfc"  # path of the model to test

[figure]
show = true
dpi = 100
save = "" #""/media/wlutz/TOSHIBA EXT/Electrical activity analysis/EV_GW/RESULTS/importance - train.png"  # empty to disable

font = "DejaVu Sans"
width = 8
height = 8
linewidth = 1
linestyle = "solid"  # dotted, dashed, dashdot, solid
color = 'blue'
alpha = 1
fill = "below" #none, above
alpha_fill = 0.3

    [figure.title]
    label = "Feature importance - EVs effect on electrical activity (harmonics filtered)"
    size = 14

    [figure.axes]

    xlabel = "Features"
    xsize = 12
    ylabel = "Relative importance [AU]"
    ysize = 12

    [figure.ticks]
    xrot = 35
    xsize = 12
    xround = 0
    nx = 20
    yrot = 0
    ysize = 12
    yround = 2
    ny = 5


