[model]
load = ""
save_model = "output/model.rfc"
save_metrics = "output/metrics.txt"

[model.train]
    targets = ["NI T48 B", "TAHV T48 B"]
    n_iter = 3

[model.test]
    metrics = true

[model.params]
        [model.params.rfc]
        n_estimators = 100
        verbose = 0
        class_weight = "balanced"
        criterion = 'gini'

[dataset]
train = "/media/wlutz/TOSHIBA EXT/Electrical activity analysis/TAHINAVIRUS/DATASETS/merge ni tahv rg27 t0 t30 t48 all donors separated_Xy_train.csv"
test = "/media/wlutz/TOSHIBA EXT/Electrical activity analysis/TAHINAVIRUS/DATASETS/merge ni tahv rg27 t0 t30 t48 all donors separated_Xy_test.csv"
target_column = "label"
