[model]
# Absolute path recquired
load = ""
save_model = "/media/wlutz/TOSHIBA EXT/Electrical activity analysis/EV_GW/MODELS/DisabledFlow Harmonics filtered train all cond T16.rfc"  # empty to disable
save_metrics = "/media/wlutz/TOSHIBA EXT/Electrical activity analysis/EV_GW/MODELS/DisabledFlow Harmonics filtered train all cond T16.txt"  # empty to disable

[model.train]
    targets = ["DisabledFlow Ctl T=16" , "DisabledFlow GW_NoEV T=16", "DisabledFlow NoGW_EV T=16", "DisabledFlow GW_EV T=16", ]
    n_iter = 3

[model.test]
    metrics = true

[model.params]
        [model.params.rfc]
        n_estimators = 100
        verbose = 0
        class_weight = "balanced"
        criterion = 'gini'

[dataset]
# empty to disable splitting
split = ""# "/media/wlutz/TOSHIBA EXT/Electrical activity analysis/EV_GW/DATASETS/Dataset_DisabledFlow_all_conditions_harmonics_filtered_merged_hours.csv"
ratio = 0.7
train = "/media/wlutz/TOSHIBA EXT/Electrical activity analysis/EV_GW/DATASETS/Dataset_DisabledFlow_all_conditions_harmonics_filtered_merged_hours_Xy_train.csv"
test = "/media/wlutz/TOSHIBA EXT/Electrical activity analysis/EV_GW/DATASETS/Dataset_DisabledFlow_all_conditions_harmonics_filtered_merged_hours_Xy_test.csv"
target_column = "label"
