[pca]
dataset ="/media/wlutz/TOSHIBA EXT/Electrical activity analysis/EV_GW/DATASETS/Dataset_DisabledFlow_all_conditions_harmonics_filtered_merged_hours.csv"
target_column = "label"
fit = ["DisabledFlow Ctl T=16", "DisabledFlow GW_NoEV T=16"]
apply = ["DisabledFlow Ctl T=16" , "DisabledFlow GW_NoEV T=16", "DisabledFlow NoGW_EV T=16", "DisabledFlow GW_EV T=16", "DisabledFlow GW_EV T=0", "DisabledFlow GW_EV T=1", "DisabledFlow GW_EV T=2", "DisabledFlow GW_EV T=3", "DisabledFlow GW_EV T=4", "DisabledFlow GW_EV T=5", "DisabledFlow GW_EV T=6", "DisabledFlow GW_EV T=7", "DisabledFlow GW_EV T=8", "DisabledFlow GW_EV T=9", "DisabledFlow GW_EV T=10", "DisabledFlow GW_EV T=11", "DisabledFlow GW_EV T=12", "DisabledFlow GW_EV T=13", "DisabledFlow GW_EV T=14", "DisabledFlow GW_EV T=15", ]
n_components = 2  # 2 or 3
show_ratio = true  # display the ratio of the components in the axis label
ellipsis = true  # Show a confidence ellipsis based on co-variance (only for 2 components)

[figure]
show = true
dpi = 100
save = ""

font = "DejaVu Sans"
width = 8
height = 8
marker_size = 12
marker = "."
colors = ['blue', 'red', 'green', 'orange', 'orange', 'orange','orange', 'orange', 'orange', 'orange', 'orange', 'orange', 'orange', 'orange', 'orange', 'orange', 'orange', 'orange', 'orange', 'orange']# ]
alphas = ["1", "1", "1", "1", "0.07","0.14","0.21","0.28","0.33","0.38","0.43","0.5","0.57","0.63","0.7","0.77","0.83","0.86","0.93","0.96",]#]

    [figure.title]
    label = "Effect of EVs on electrical activity"
    size = 14

    [figure.axes]

    xlabel = "Principal component 1"
    xsize = 12
    ylabel = "Principal component 2"
    ysize = 12
    zlabel = "Principal component 3"
    zsize = 12

    [figure.ticks]
    xrot = 45
    xsize = 12
    xround = 2
    nx = 15

    yrot = 0
    ysize = 12
    yround = 2
    ny = 15

    zrot = 0
    zsize = 12
    zround = 2
    nz = 5

    [figure.legend]
    enable = true
    draggable = true
    n_cols = 1
    size = 12
    alpha = 1
    framealpha = 0.5
    anchor = "best" # ['best', 'upper left', 'upper right', 'lower left', 'lower right', 'upper center', 'lower center', 'center left', 'center right', 'center', 'custom']
    xpos = 0
    ypos = 0